apiVersion: v1
kind: Pod
metadata:
  labels:
    role: jenkins-slave
  name: build-pod
spec:
  containers:
    - name: skopeo
      image: image-registry.openshift-image-registry.svc:5000/ebo-cicd/skopeo
      args:
        - /bin/sh
        - -c
        - touch /tmp/healthy
      livenessProbe:
        exec:
          command:
            - cat
            - /tmp/healthy
        initialDelaySeconds: 5
        periodSeconds: 5
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
          readOnly: false
        - mountPath: /etc/config
          name: config-volume
    - name: python
      image: image-registry.openshift-image-registry.svc:5000/ebo-python-builder/python-builder:latest
      command:
        - cat
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
          readOnly: false
        - mountPath: /etc/config
          name: config-volume
      tty: true
    - name: jnlp
      image: jenkins/jnlp-slave:latest
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
          readOnly: false
  volumes:
    - emptyDir: {}
      name: workspace-volume
    - name: config-volume
      configMap:
        name: pipeline-config