apiVersion: v1
kind: Template
objects:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app.openshift.io/vcs-ref: ${BRANCH}
        app.openshift.io/vcs-uri: ${REPO}
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
      namespace: NAMESPACE
    spec:
      clusterIP: {}
      ports:
        - name: 8088-tcp
          port: 8088
          protocol: TCP
          targetPort: 8088
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      sessionAffinity: None
      type: ClusterIP
    status:
      loadBalancer: {}
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    metadata:
      annotations:
        app.openshift.io/vcs-ref: ${BRANCH}
        app.openshift.io/vcs-uri: ${REPO}
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE}
    spec:
      lookupPolicy:
        local: false
      tags:
        - from:
            kind: ImageStreamImage
            name: ${APP_NAME}
            namespace: ${NAMESPACE}
          importPolicy: {}
          name: 0.0-0
          referencePolicy:
            type: Source
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      annotations:
        app.openshift.io/vcs-ref: ${BRANCH}
        app.openshift.io/vcs-uri: ${REPO}
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE}
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: null
      output:
        to:
          kind: ImageStreamTag
          name: ${APP_NAME}:latest
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        contextDir: /
        git:
          ref: ${BRANCH}
          uri: ${REPO}
        type: Git
      strategy:
        dockerStrategy:
          dockerfilePath: src/resources/container/client.Dockerfile
          env:
            - name: BIND_PORT
              valueFrom:
                configMapKeyRef:
                  key: BIND_PORT
                  name: refactored-memory
            - name: NEXUS_HOSTNAME
              valueFrom:
                configMapKeyRef:
                  key: NEXUS_HOSTNAME
                  name: refactored-memory
            - name: PYPI_GROUP_REPO
              valueFrom:
                configMapKeyRef:
                  key: PYPI_GROUP_REPO
                  name: refactored-memory
            - name: NAMESPACE
              value: ${NAMESPACE}
        type: Docker
      successfulBuildsHistoryLimit: 5
      triggers:
        - generic:
            secretReference:
              name: ${APP_NAME}-generic-webhook-secret
          type: Generic
        - github:
            secretReference:
              name: ${APP_NAME}-github-webhook-secret
          type: GitHub
        - type: ConfigChange
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    metadata:
      annotations:
        app.openshift.io/vcs-ref: ${BRANCH}
        app.openshift.io/vcs-uri: ${REPO}
      labels:
        app: ${APP_NAME}
      name: ${APP_NAME}
      namespace: ${NAMESPACE}
    spec:
      replicas: 1
      revisionHistoryLimit: 10
      selector:
        app: ${APP_NAME}
        deploymentconfig: ${APP_NAME}
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: ${APP_NAME}
            deploymentconfig: ${APP_NAME}
        spec:
          containers:
            - env:
              - name: VERSION
                value: 0.0-21 (${APP_NAME}-dev)
              - name: PORT
                valueFrom:
                  configMapKeyRef:
                    key: BIND_PORT
                    name: refactored-memory
            image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${APP_NAME}
            imagePullPolicy: Always
            name: ${APP_NAME}
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - imageChangeParams:
            automatic: true
            containerNames:
              - ${APP_NAME}
            from:
              kind: ImageStreamTag
              name: ${APP_NAME}:latest
              namespace: ${NAMESPACE}
            lastTriggeredImage: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/${APP_NAME}
          type: ImageChange
        - type: ConfigChange
parameters:
  - name: APP_NAME
    value: refactored-memory-client
  - name: REPO
    value: https://github.com/ericboyer/refactored-memory.git
  - name: BRANCH
    value: feature/webui
  - name: NAMESPACE
    value: refactored-memory-dev