apiVersion: v1
kind: List
items:
- apiVersion: v1
  data:
    .pypirc: |
      [distutils]
      index-servers = pypi-internal

      [pypi-internal]
      repository: http://nexusrepo-sonatype-nexus-service-ebo-cicd.apps.ccsd4.na-1.rht-labs.com/repository/pypi-dev/
      username: admin
      password: <password>
    BIND_PORT: "8088"
    NEXUS_HOSTNAME: nexusrepo-sonatype-nexus-service-ebo-cicd.apps.ccsd4.na-1.rht-labs.com
    PYPI_GROUP_REPO: repository/pypi-public/simple
    NAMESPACE: refactored-memory-dev
  kind: ConfigMap
  metadata:
    name: pipeline-config