---
apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
  annotations:
    app.openshfit.io/display-name: Pipeline build config for python server demo
objects:
  - apiVersion: build.openshift.io/v1
    kind: BuildConfig
    metadata:
      labels:
        build: ${NAME}
      name: ${NAME}
    spec:
      failedBuildsHistoryLimit: 5
      nodeSelector: {}
      output: {}
      postCommit: {}
      resources: {}
      runPolicy: Serial
      source:
        git:
          ref: ${BRANCH}
          uri: ${REPO}
        type: Git
      strategy:
        jenkinsPipelineStrategy:
          jenkinsfilePath: ${JENKINSFILE_PATH}
        type: JenkinsPipeline
parameters:
  - name: NAME
    value: refactored-memory
    description: The application name that all objects will be assigned.
  - name: REPO
    value: https://github.com/ericboyer/refactored-memory.git
    description: The source repository
  - name: BRANCH
    value: master
    description: The repository branch to reference
  - name: JENKINSFILE_PATH
    value: src/resources/pipeline/Jenkinsfile
    description: Path to the Jenkinsfile for this pipeline