---
apiVersion: v1
kind: Template
metadata:
  name: refactored-memory
  annotations:
    app.openshfit.io/display-name: Deployment template for server-side python application demonstration.
objects:
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: refactored-memory
      labels:
        app: ${APP_NAME}
    data:
      .pypirc: |
        [distutils]
        index-servers = pypi-internal

        [pypi-internal]
        repository: http://nexusrepo-sonatype-nexus-service-${PIPELINES_NAMESPACE}.apps.${CLUSTER_SUBDOMAIN}/repository/pypi-dev/
        username: admin
        password: admin123
      BIND_PORT: "8088"
      RUN_PORT: "8080"
      NEXUS_HOSTNAME: nexusrepo-sonatype-nexus-service-${PIPELINES_NAMESPACE}.apps.${CLUSTER_SUBDOMAIN}
      PYPI_GROUP_REPO: repository/pypi-public/simple
  - apiVersion: authorization.openshift.io/v1
    kind: RoleBinding
    metadata:
      name: edit
      labels:
        app: ${APP_NAME}
    roleRef:
      name: edit
    subjects:
      - kind: ServiceAccount
        name: jenkins
        namespace: ${PIPELINES_NAMESPACE}
    userNames:
      - system:serviceaccount:${PIPELINES_NAMESPACE}:jenkins
parameters:
  - name: APP_NAME
    value: refactored-memory
    description: The application name that all objects will be assigned.
  - name: PIPELINES_NAMESPACE
    value: ebo-cicd
    description: The namespace for all ci/cd tooling
  - name: CLUSTER_SUBDOMAIN
    value: ccsd4.na-1.rht-labs.com
    description: The subdomain of the OpenShift cluster