apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    role: "jenkins-slave"
  name: "build-pod"
spec:
  containers:
    - image: "docker-registry.default.svc:5000/ebo-cicd/python-38:latest"
      command:
        - cat
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
      name: "python"
      tty: true
    - image: "jenkins/jnlp-slave:3.35-5-alpine"
      name: "jnlp"
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
  volumes:
    - emptyDir: {}
      name: "workspace-volume"