---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: backend
  name: backend
spec:
  lookupPolicy:
    local: false
---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: backend
  name: backend
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: backend:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    contextDir: /
    git:
      ref: feature/tektonci
      uri: https://github.com/ericboyer/refactored-memory.git
    type: Git
  strategy:
    dockerStrategy:
      dockerfilePath: src/resources/container/server.Dockerfile
      env:
        - name: BIND_PORT
          valueFrom:
            configMapKeyRef:
              key: BIND_PORT
              name: refactored-memory
        - name: NEXUS_HOSTNAME
          valueFrom:
            configMapKeyRef:
              key: NEXUS_HOSTNAME
              name: refactored-memory
        - name: PYPI_GROUP_REPO
          valueFrom:
            configMapKeyRef:
              key: PYPI_GROUP_REPO
              name: refactored-memory
        - name: NAMESPACE
          value: ebo-pipelines
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
    - type: ConfigChange
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
  name: backend
spec:
  ports:
    - name: 8088-tcp
      port: 8088
      protocol: TCP
      targetPort: 8088
  selector:
    app: backend
    deploymentconfig: backend
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
labels:
  app: backend
name: backend
spec:
replicas: 1
revisionHistoryLimit: 5
selector:
  app: backend
  deploymentconfig: backend
strategy:
  activeDeadlineSeconds: 21600
  resources: {}
  rollingParams:
    intervalSeconds: 1
    maxSurge: 25%
    maxUnavailable: 25%
    timeoutSeconds: 600
    updatePeriodSeconds: 1
  type: Rolling
template:
  metadata:
    labels:
      app: backend
      deploymentconfig: backend
  spec:
    containers:
      - env:
        - name: VERSION
          value: 0.0.0 (backend-dev)
        - name: PORT
          valueFrom:
            configMapKeyRef:
              key: BIND_PORT
              name: refactored-memory
        image: image-registry.openshift-image-registry.svc:5000/ebo-pipelines/backend
        imagePullPolicy: Always
        name: backend
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
    dnsPolicy: ClusterFirst
    restartPolicy: Always
    schedulerName: default-scheduler
    securityContext: {}
    terminationGracePeriodSeconds: 30
test: false
triggers: []