apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    role: "jenkins-slave"
  name: "build-pod"
spec:
  containers:
#$> oc import-image ubi8/python-38 --from=registry.access.redhat.com/ubi8/python-38 --confirm
    - image: "registry.access.redhat.com/ubi8/python-38:1-22"
      command:
        - cat
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
        - mountPath: "/etc/config"
          name: "config-volume"
      name: "python"
      tty: true
    - image: "jenkins/jnlp-slave:3.35-5-alpine"
      name: "jnlp"
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
  volumes:
    - emptyDir: {}
      name: "workspace-volume"
    - name: "config-volume"
      configMap:
        name: pypirc-config