apiVersion: v1
kind: Pod
metadata:
  labels:
    role: jenkins-slave
  name: build-pod
spec:
  containers:
    - image: registry.redhat.io/rhel8/skopeo:8.2
      name: skopeo
      command:
        - cat
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
          readOnly: false
        - mountPath: /etc/config
          name: config-volume
    - image: docker-registry.default.svc:5000/ebo-python-builder/python-builder:latest
      command:
        - cat
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
          readOnly: false
        - mountPath: /etc/config
          name: config-volume
      name: python
      tty: true
    - name: jnlp
      image: jenkins/jnlp-slave:latest
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: /home/jenkins
          name: workspace-volume
          readOnly: false
  volumes:
    - emptyDir: {}
      name: workspace-volume
    - name: config-volume
      configMap:
        name: pypirc-config