apiVersion: "v1"
kind: "Pod"
metadata:
  labels:
    role: "jenkins-slave"
  name: "build-pod"
spec:
  containers:
#$> oc import-image ubi8/python-38 --from=registry.access.redhat.com/ubi8/python-38 --confirm
    - image: "registry.access.redhat.com/ubi8/python-38:1-22"
      command:
        - cat
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
        - mountPath: "/etc/config"
          name: "config-volume"
      name: "python"
      tty: true
    - name: "jnlp"
      image: "quay.io/openshift/origin-jenkins-agent-base"
#      image: "registry.access.redhat.com/openshift3/jenkins-slave-base-rhel7"
#      image: "jenkins/jnlp-slave:latest"
#      image: "registry.redhat.io/openshift4/ose-jenkins-agent-base:v4.4.0"
      env:
        - name: HOME
          value: /home/jenkins
      volumeMounts:
        - mountPath: "/home/jenkins"
          name: "workspace-volume"
          readOnly: false
  volumes:
    - emptyDir: {}
      name: "workspace-volume"
    - name: "config-volume"
      configMap:
        name: pypirc-config