apiVersion: v1
kind: ConfigMap
metadata:
  name: refactored-memory
data:
  .pypirc: |
    [distutils]
    index-servers = pypi-internal

    [pypi-internal]
    repository: http://nexusrepo-sonatype-nexus-service-${CICD_NAMESPACE}.apps.${CLUSTER_SUBDOMAIN}/repository/pypi-dev/
    username: admin
    password: admin123
  BIND_PORT: "8088"
  RUN_PORT: "8080"
  NEXUS_HOSTNAME: nexusrepo-sonatype-nexus-service-${CICD_NAMESPACE}.apps.${CLUSTER_SUBDOMAIN}
  PYPI_GROUP_REPO: repository/pypi-public/simple